server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: reader
    password: 123456
    druid:
      initial-size: 5 #杩炴帴姹犲垵濮嬪寲澶у皬
      min-idle: 10 #鏈€灏忕┖闂茶繛鎺ユ暟
      max-active: 20 #鏈€澶ц繛鎺ユ暟
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #涓嶇粺璁¤繖浜涜姹傛暟鎹?
      stat-view-servlet: #璁块棶鐩戞帶缃戦〉鐨勭櫥褰曠敤鎴峰悕鍜屽瘑鐮?
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: mongo
      port: 27017
      database: mall-port
    redis:
      host: redis # Redis鏈嶅姟鍣ㄥ湴鍧€
      database: 0 # Redis鏁版嵁搴撶储寮曪紙榛樿涓?0锛?
      port: 6379 # Redis鏈嶅姟鍣ㄨ繛鎺ョ鍙?
      password: # Redis鏈嶅姟鍣ㄨ繛鎺ュ瘑鐮侊紙榛樿涓虹┖锛?
      timeout: 300ms # 杩炴帴瓒呮椂鏃堕棿锛堟绉掞級
  rabbitmq:
    host: rabbit
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall

mongo:
  insert:
    sqlEnable: true # 鐢ㄤ簬鎺у埗鏄惁閫氳繃鏁版嵁搴撴暟鎹潵鎻掑叆mongo

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info

logstash:
  host: logstash

alipay:
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  appId: your appId
  alipayPublicKey: your alipayPublicKey
  appPrivateKey: your appPrivateKey
  returnUrl: http://10.10.17.50:8060/#/pages/money/paySuccess
  notifyUrl:

